before_script:
 - export GOROOT=/data/service/go-1.12.4
 - export GO111MODULE=on
 - export PATH=$PATH:$GOROOT/bin
 - export GOPATH=/data/golang
 - export GO_PROJECT_NAMESPACE="$GOPATH/src/github.com/$CI_PROJECT_NAMESPACE"
 - mkdir -p $GO_PROJECT_NAMESPACE
 - ln -srf $CI_PROJECT_DIR $GO_PROJECT_NAMESPACE
 - export GO_PROJECT_DIR=$GO_PROJECT_NAMESPACE/$CI_PROJECT_NAME
 - cd $GO_PROJECT_DIR

master:
 stage: build
 script:
 - make
 - echo > ./Dockerfile
 - echo "FROM docker-harbor/base/golang:with-ffmpeg" >> ./Dockerfile
 - echo "ADD ${CI_PROJECT_NAME}_server /data/service" >> ./Dockerfile
 - echo "ADD ${CI_PROJECT_NAME}_cron /data/service" >> ./Dockerfile
 - echo "ADD ${CI_PROJECT_NAME}_scheduler /data/service" >> ./Dockerfile
 - echo "ADD ${CI_PROJECT_NAME}_http /data/service" >> ./Dockerfile
 - echo "ADD . /data/service" >> ./Dockerfile
 - echo "RUN touch /data/service/app.properties" >> ./Dockerfile
 - echo "CMD [\"${CI_PROJECT_NAME}_server\"]" >> ./Dockerfile
 - docker build -t docker-harborn/${CI_PROJECT_NAMESPACE,,}/${CI_PROJECT_NAME,,}:${CI_COMMIT_TAG,,} .
 - docker push docker-harbor/${CI_PROJECT_NAMESPACE,,}/${CI_PROJECT_NAME,,}:${CI_COMMIT_TAG,,}
 - echo "docker path is docker-harbor/${CI_PROJECT_NAMESPACE,,}/${CI_PROJECT_NAME,,}:${CI_COMMIT_TAG,,}"
 only:
 - tags
