// Code generated by protoc-gen-go. DO NOT EDIT.
// source: termite.proto

package termite

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 添加工作流任务
type AddWorkFlowRequest struct {
	WorkflowKey          string            `protobuf:"bytes,1,opt,name=workflow_key,json=workflowKey,proto3" json:"workflow_key,omitempty"`
	Project              string            `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Env                  map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cid                  string            `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddWorkFlowRequest) Reset()         { *m = AddWorkFlowRequest{} }
func (m *AddWorkFlowRequest) String() string { return proto.CompactTextString(m) }
func (*AddWorkFlowRequest) ProtoMessage()    {}
func (*AddWorkFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{0}
}

func (m *AddWorkFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWorkFlowRequest.Unmarshal(m, b)
}
func (m *AddWorkFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWorkFlowRequest.Marshal(b, m, deterministic)
}
func (m *AddWorkFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWorkFlowRequest.Merge(m, src)
}
func (m *AddWorkFlowRequest) XXX_Size() int {
	return xxx_messageInfo_AddWorkFlowRequest.Size(m)
}
func (m *AddWorkFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWorkFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddWorkFlowRequest proto.InternalMessageInfo

func (m *AddWorkFlowRequest) GetWorkflowKey() string {
	if m != nil {
		return m.WorkflowKey
	}
	return ""
}

func (m *AddWorkFlowRequest) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AddWorkFlowRequest) GetEnv() map[string]string {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *AddWorkFlowRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type AddWorkFlowResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddWorkFlowResponse) Reset()         { *m = AddWorkFlowResponse{} }
func (m *AddWorkFlowResponse) String() string { return proto.CompactTextString(m) }
func (*AddWorkFlowResponse) ProtoMessage()    {}
func (*AddWorkFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{1}
}

func (m *AddWorkFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddWorkFlowResponse.Unmarshal(m, b)
}
func (m *AddWorkFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddWorkFlowResponse.Marshal(b, m, deterministic)
}
func (m *AddWorkFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddWorkFlowResponse.Merge(m, src)
}
func (m *AddWorkFlowResponse) XXX_Size() int {
	return xxx_messageInfo_AddWorkFlowResponse.Size(m)
}
func (m *AddWorkFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddWorkFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddWorkFlowResponse proto.InternalMessageInfo

func (m *AddWorkFlowResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddWorkFlowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 修复/重置 工作流
type RecoverWorkFlowRequest struct {
	FlowId               int64    `protobuf:"varint,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverWorkFlowRequest) Reset()         { *m = RecoverWorkFlowRequest{} }
func (m *RecoverWorkFlowRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverWorkFlowRequest) ProtoMessage()    {}
func (*RecoverWorkFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{2}
}

func (m *RecoverWorkFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverWorkFlowRequest.Unmarshal(m, b)
}
func (m *RecoverWorkFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverWorkFlowRequest.Marshal(b, m, deterministic)
}
func (m *RecoverWorkFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverWorkFlowRequest.Merge(m, src)
}
func (m *RecoverWorkFlowRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverWorkFlowRequest.Size(m)
}
func (m *RecoverWorkFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverWorkFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverWorkFlowRequest proto.InternalMessageInfo

func (m *RecoverWorkFlowRequest) GetFlowId() int64 {
	if m != nil {
		return m.FlowId
	}
	return 0
}

type RecoverWorkFlowResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverWorkFlowResponse) Reset()         { *m = RecoverWorkFlowResponse{} }
func (m *RecoverWorkFlowResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverWorkFlowResponse) ProtoMessage()    {}
func (*RecoverWorkFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{3}
}

func (m *RecoverWorkFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverWorkFlowResponse.Unmarshal(m, b)
}
func (m *RecoverWorkFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverWorkFlowResponse.Marshal(b, m, deterministic)
}
func (m *RecoverWorkFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverWorkFlowResponse.Merge(m, src)
}
func (m *RecoverWorkFlowResponse) XXX_Size() int {
	return xxx_messageInfo_RecoverWorkFlowResponse.Size(m)
}
func (m *RecoverWorkFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverWorkFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverWorkFlowResponse proto.InternalMessageInfo

func (m *RecoverWorkFlowResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RecoverWorkFlowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 添加工作流上下文
type SetWorkFlowContextRequest struct {
	FlowId               int64             `protobuf:"varint,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Context              map[string]string `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SetWorkFlowContextRequest) Reset()         { *m = SetWorkFlowContextRequest{} }
func (m *SetWorkFlowContextRequest) String() string { return proto.CompactTextString(m) }
func (*SetWorkFlowContextRequest) ProtoMessage()    {}
func (*SetWorkFlowContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{4}
}

func (m *SetWorkFlowContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetWorkFlowContextRequest.Unmarshal(m, b)
}
func (m *SetWorkFlowContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetWorkFlowContextRequest.Marshal(b, m, deterministic)
}
func (m *SetWorkFlowContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetWorkFlowContextRequest.Merge(m, src)
}
func (m *SetWorkFlowContextRequest) XXX_Size() int {
	return xxx_messageInfo_SetWorkFlowContextRequest.Size(m)
}
func (m *SetWorkFlowContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetWorkFlowContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetWorkFlowContextRequest proto.InternalMessageInfo

func (m *SetWorkFlowContextRequest) GetFlowId() int64 {
	if m != nil {
		return m.FlowId
	}
	return 0
}

func (m *SetWorkFlowContextRequest) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

type SetWorkFlowContextResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetWorkFlowContextResponse) Reset()         { *m = SetWorkFlowContextResponse{} }
func (m *SetWorkFlowContextResponse) String() string { return proto.CompactTextString(m) }
func (*SetWorkFlowContextResponse) ProtoMessage()    {}
func (*SetWorkFlowContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{5}
}

func (m *SetWorkFlowContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetWorkFlowContextResponse.Unmarshal(m, b)
}
func (m *SetWorkFlowContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetWorkFlowContextResponse.Marshal(b, m, deterministic)
}
func (m *SetWorkFlowContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetWorkFlowContextResponse.Merge(m, src)
}
func (m *SetWorkFlowContextResponse) XXX_Size() int {
	return xxx_messageInfo_SetWorkFlowContextResponse.Size(m)
}
func (m *SetWorkFlowContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetWorkFlowContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetWorkFlowContextResponse proto.InternalMessageInfo

func (m *SetWorkFlowContextResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SetWorkFlowContextResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 查询工作流上下文
type GetWorkFlowContextRequest struct {
	FlowId               int64    `protobuf:"varint,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkFlowContextRequest) Reset()         { *m = GetWorkFlowContextRequest{} }
func (m *GetWorkFlowContextRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkFlowContextRequest) ProtoMessage()    {}
func (*GetWorkFlowContextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{6}
}

func (m *GetWorkFlowContextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkFlowContextRequest.Unmarshal(m, b)
}
func (m *GetWorkFlowContextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkFlowContextRequest.Marshal(b, m, deterministic)
}
func (m *GetWorkFlowContextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkFlowContextRequest.Merge(m, src)
}
func (m *GetWorkFlowContextRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkFlowContextRequest.Size(m)
}
func (m *GetWorkFlowContextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkFlowContextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkFlowContextRequest proto.InternalMessageInfo

func (m *GetWorkFlowContextRequest) GetFlowId() int64 {
	if m != nil {
		return m.FlowId
	}
	return 0
}

type GetWorkFlowContextResponse struct {
	Code                 int64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Context              map[string]string `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetWorkFlowContextResponse) Reset()         { *m = GetWorkFlowContextResponse{} }
func (m *GetWorkFlowContextResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkFlowContextResponse) ProtoMessage()    {}
func (*GetWorkFlowContextResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{7}
}

func (m *GetWorkFlowContextResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkFlowContextResponse.Unmarshal(m, b)
}
func (m *GetWorkFlowContextResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkFlowContextResponse.Marshal(b, m, deterministic)
}
func (m *GetWorkFlowContextResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkFlowContextResponse.Merge(m, src)
}
func (m *GetWorkFlowContextResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkFlowContextResponse.Size(m)
}
func (m *GetWorkFlowContextResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkFlowContextResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkFlowContextResponse proto.InternalMessageInfo

func (m *GetWorkFlowContextResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetWorkFlowContextResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetWorkFlowContextResponse) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

// 查询工作通过cid vflow vwork
type WorkResult struct {
	Cid                  string   `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	WorkId               int64    `protobuf:"varint,2,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	WorkState            int64    `protobuf:"varint,3,opt,name=work_state,json=workState,proto3" json:"work_state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkResult) Reset()         { *m = WorkResult{} }
func (m *WorkResult) String() string { return proto.CompactTextString(m) }
func (*WorkResult) ProtoMessage()    {}
func (*WorkResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{8}
}

func (m *WorkResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkResult.Unmarshal(m, b)
}
func (m *WorkResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkResult.Marshal(b, m, deterministic)
}
func (m *WorkResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkResult.Merge(m, src)
}
func (m *WorkResult) XXX_Size() int {
	return xxx_messageInfo_WorkResult.Size(m)
}
func (m *WorkResult) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkResult.DiscardUnknown(m)
}

var xxx_messageInfo_WorkResult proto.InternalMessageInfo

func (m *WorkResult) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *WorkResult) GetWorkId() int64 {
	if m != nil {
		return m.WorkId
	}
	return 0
}

func (m *WorkResult) GetWorkState() int64 {
	if m != nil {
		return m.WorkState
	}
	return 0
}

type QueryWorkRequest struct {
	WorkflowKey          string   `protobuf:"bytes,1,opt,name=workflow_key,json=workflowKey,proto3" json:"workflow_key,omitempty"`
	WorkKey              string   `protobuf:"bytes,2,opt,name=work_key,json=workKey,proto3" json:"work_key,omitempty"`
	Cid                  string   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryWorkRequest) Reset()         { *m = QueryWorkRequest{} }
func (m *QueryWorkRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWorkRequest) ProtoMessage()    {}
func (*QueryWorkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{9}
}

func (m *QueryWorkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWorkRequest.Unmarshal(m, b)
}
func (m *QueryWorkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWorkRequest.Marshal(b, m, deterministic)
}
func (m *QueryWorkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkRequest.Merge(m, src)
}
func (m *QueryWorkRequest) XXX_Size() int {
	return xxx_messageInfo_QueryWorkRequest.Size(m)
}
func (m *QueryWorkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkRequest proto.InternalMessageInfo

func (m *QueryWorkRequest) GetWorkflowKey() string {
	if m != nil {
		return m.WorkflowKey
	}
	return ""
}

func (m *QueryWorkRequest) GetWorkKey() string {
	if m != nil {
		return m.WorkKey
	}
	return ""
}

func (m *QueryWorkRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type QueryWorkResponse struct {
	Works                []*WorkResult `protobuf:"bytes,1,rep,name=works,proto3" json:"works,omitempty"`
	Code                 int64         `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string        `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *QueryWorkResponse) Reset()         { *m = QueryWorkResponse{} }
func (m *QueryWorkResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWorkResponse) ProtoMessage()    {}
func (*QueryWorkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{10}
}

func (m *QueryWorkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWorkResponse.Unmarshal(m, b)
}
func (m *QueryWorkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWorkResponse.Marshal(b, m, deterministic)
}
func (m *QueryWorkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkResponse.Merge(m, src)
}
func (m *QueryWorkResponse) XXX_Size() int {
	return xxx_messageInfo_QueryWorkResponse.Size(m)
}
func (m *QueryWorkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkResponse proto.InternalMessageInfo

func (m *QueryWorkResponse) GetWorks() []*WorkResult {
	if m != nil {
		return m.Works
	}
	return nil
}

func (m *QueryWorkResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryWorkResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 查询工作流通过cid vflow
type QueryWorkFlowRequest struct {
	WorkflowKey          string   `protobuf:"bytes,1,opt,name=workflow_key,json=workflowKey,proto3" json:"workflow_key,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryWorkFlowRequest) Reset()         { *m = QueryWorkFlowRequest{} }
func (m *QueryWorkFlowRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWorkFlowRequest) ProtoMessage()    {}
func (*QueryWorkFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{11}
}

func (m *QueryWorkFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWorkFlowRequest.Unmarshal(m, b)
}
func (m *QueryWorkFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWorkFlowRequest.Marshal(b, m, deterministic)
}
func (m *QueryWorkFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkFlowRequest.Merge(m, src)
}
func (m *QueryWorkFlowRequest) XXX_Size() int {
	return xxx_messageInfo_QueryWorkFlowRequest.Size(m)
}
func (m *QueryWorkFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkFlowRequest proto.InternalMessageInfo

func (m *QueryWorkFlowRequest) GetWorkflowKey() string {
	if m != nil {
		return m.WorkflowKey
	}
	return ""
}

func (m *QueryWorkFlowRequest) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type QueryWorkFlowResponse struct {
	FlowId               int64    `protobuf:"varint,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryWorkFlowResponse) Reset()         { *m = QueryWorkFlowResponse{} }
func (m *QueryWorkFlowResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWorkFlowResponse) ProtoMessage()    {}
func (*QueryWorkFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{12}
}

func (m *QueryWorkFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryWorkFlowResponse.Unmarshal(m, b)
}
func (m *QueryWorkFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryWorkFlowResponse.Marshal(b, m, deterministic)
}
func (m *QueryWorkFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWorkFlowResponse.Merge(m, src)
}
func (m *QueryWorkFlowResponse) XXX_Size() int {
	return xxx_messageInfo_QueryWorkFlowResponse.Size(m)
}
func (m *QueryWorkFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWorkFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWorkFlowResponse proto.InternalMessageInfo

func (m *QueryWorkFlowResponse) GetFlowId() int64 {
	if m != nil {
		return m.FlowId
	}
	return 0
}

func (m *QueryWorkFlowResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryWorkFlowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 工作流结束
type FinishWorkFlowRequest struct {
	FlowId               int64    `protobuf:"varint,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishWorkFlowRequest) Reset()         { *m = FinishWorkFlowRequest{} }
func (m *FinishWorkFlowRequest) String() string { return proto.CompactTextString(m) }
func (*FinishWorkFlowRequest) ProtoMessage()    {}
func (*FinishWorkFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{13}
}

func (m *FinishWorkFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishWorkFlowRequest.Unmarshal(m, b)
}
func (m *FinishWorkFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishWorkFlowRequest.Marshal(b, m, deterministic)
}
func (m *FinishWorkFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishWorkFlowRequest.Merge(m, src)
}
func (m *FinishWorkFlowRequest) XXX_Size() int {
	return xxx_messageInfo_FinishWorkFlowRequest.Size(m)
}
func (m *FinishWorkFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishWorkFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinishWorkFlowRequest proto.InternalMessageInfo

func (m *FinishWorkFlowRequest) GetFlowId() int64 {
	if m != nil {
		return m.FlowId
	}
	return 0
}

type FinishWorkFlowResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinishWorkFlowResponse) Reset()         { *m = FinishWorkFlowResponse{} }
func (m *FinishWorkFlowResponse) String() string { return proto.CompactTextString(m) }
func (*FinishWorkFlowResponse) ProtoMessage()    {}
func (*FinishWorkFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{14}
}

func (m *FinishWorkFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinishWorkFlowResponse.Unmarshal(m, b)
}
func (m *FinishWorkFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinishWorkFlowResponse.Marshal(b, m, deterministic)
}
func (m *FinishWorkFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinishWorkFlowResponse.Merge(m, src)
}
func (m *FinishWorkFlowResponse) XXX_Size() int {
	return xxx_messageInfo_FinishWorkFlowResponse.Size(m)
}
func (m *FinishWorkFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinishWorkFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinishWorkFlowResponse proto.InternalMessageInfo

func (m *FinishWorkFlowResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FinishWorkFlowResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 工作开始
type WorkStartRequest struct {
	WorkId               int64    `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkStartRequest) Reset()         { *m = WorkStartRequest{} }
func (m *WorkStartRequest) String() string { return proto.CompactTextString(m) }
func (*WorkStartRequest) ProtoMessage()    {}
func (*WorkStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{15}
}

func (m *WorkStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkStartRequest.Unmarshal(m, b)
}
func (m *WorkStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkStartRequest.Marshal(b, m, deterministic)
}
func (m *WorkStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkStartRequest.Merge(m, src)
}
func (m *WorkStartRequest) XXX_Size() int {
	return xxx_messageInfo_WorkStartRequest.Size(m)
}
func (m *WorkStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkStartRequest proto.InternalMessageInfo

func (m *WorkStartRequest) GetWorkId() int64 {
	if m != nil {
		return m.WorkId
	}
	return 0
}

type WorkStartResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkStartResponse) Reset()         { *m = WorkStartResponse{} }
func (m *WorkStartResponse) String() string { return proto.CompactTextString(m) }
func (*WorkStartResponse) ProtoMessage()    {}
func (*WorkStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{16}
}

func (m *WorkStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkStartResponse.Unmarshal(m, b)
}
func (m *WorkStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkStartResponse.Marshal(b, m, deterministic)
}
func (m *WorkStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkStartResponse.Merge(m, src)
}
func (m *WorkStartResponse) XXX_Size() int {
	return xxx_messageInfo_WorkStartResponse.Size(m)
}
func (m *WorkStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkStartResponse proto.InternalMessageInfo

func (m *WorkStartResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkStartResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 工作结束
type WorkFinishRequest struct {
	WorkId               int64    `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Result               string   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Output               string   `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkFinishRequest) Reset()         { *m = WorkFinishRequest{} }
func (m *WorkFinishRequest) String() string { return proto.CompactTextString(m) }
func (*WorkFinishRequest) ProtoMessage()    {}
func (*WorkFinishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{17}
}

func (m *WorkFinishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkFinishRequest.Unmarshal(m, b)
}
func (m *WorkFinishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkFinishRequest.Marshal(b, m, deterministic)
}
func (m *WorkFinishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkFinishRequest.Merge(m, src)
}
func (m *WorkFinishRequest) XXX_Size() int {
	return xxx_messageInfo_WorkFinishRequest.Size(m)
}
func (m *WorkFinishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkFinishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkFinishRequest proto.InternalMessageInfo

func (m *WorkFinishRequest) GetWorkId() int64 {
	if m != nil {
		return m.WorkId
	}
	return 0
}

func (m *WorkFinishRequest) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *WorkFinishRequest) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type WorkFinishResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkFinishResponse) Reset()         { *m = WorkFinishResponse{} }
func (m *WorkFinishResponse) String() string { return proto.CompactTextString(m) }
func (*WorkFinishResponse) ProtoMessage()    {}
func (*WorkFinishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{18}
}

func (m *WorkFinishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkFinishResponse.Unmarshal(m, b)
}
func (m *WorkFinishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkFinishResponse.Marshal(b, m, deterministic)
}
func (m *WorkFinishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkFinishResponse.Merge(m, src)
}
func (m *WorkFinishResponse) XXX_Size() int {
	return xxx_messageInfo_WorkFinishResponse.Size(m)
}
func (m *WorkFinishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkFinishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkFinishResponse proto.InternalMessageInfo

func (m *WorkFinishResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkFinishResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 工作异常
type WorkErrorRequest struct {
	WorkId               int64    `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkErrorRequest) Reset()         { *m = WorkErrorRequest{} }
func (m *WorkErrorRequest) String() string { return proto.CompactTextString(m) }
func (*WorkErrorRequest) ProtoMessage()    {}
func (*WorkErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{19}
}

func (m *WorkErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkErrorRequest.Unmarshal(m, b)
}
func (m *WorkErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkErrorRequest.Marshal(b, m, deterministic)
}
func (m *WorkErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkErrorRequest.Merge(m, src)
}
func (m *WorkErrorRequest) XXX_Size() int {
	return xxx_messageInfo_WorkErrorRequest.Size(m)
}
func (m *WorkErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkErrorRequest proto.InternalMessageInfo

func (m *WorkErrorRequest) GetWorkId() int64 {
	if m != nil {
		return m.WorkId
	}
	return 0
}

func (m *WorkErrorRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type WorkErrorResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkErrorResponse) Reset()         { *m = WorkErrorResponse{} }
func (m *WorkErrorResponse) String() string { return proto.CompactTextString(m) }
func (*WorkErrorResponse) ProtoMessage()    {}
func (*WorkErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{20}
}

func (m *WorkErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkErrorResponse.Unmarshal(m, b)
}
func (m *WorkErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkErrorResponse.Marshal(b, m, deterministic)
}
func (m *WorkErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkErrorResponse.Merge(m, src)
}
func (m *WorkErrorResponse) XXX_Size() int {
	return xxx_messageInfo_WorkErrorResponse.Size(m)
}
func (m *WorkErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkErrorResponse proto.InternalMessageInfo

func (m *WorkErrorResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkErrorResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 工作延迟
type WorkDelayRequest struct {
	WorkId               int64    `protobuf:"varint,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	DelaySeconds         int64    `protobuf:"varint,2,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkDelayRequest) Reset()         { *m = WorkDelayRequest{} }
func (m *WorkDelayRequest) String() string { return proto.CompactTextString(m) }
func (*WorkDelayRequest) ProtoMessage()    {}
func (*WorkDelayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{21}
}

func (m *WorkDelayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkDelayRequest.Unmarshal(m, b)
}
func (m *WorkDelayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkDelayRequest.Marshal(b, m, deterministic)
}
func (m *WorkDelayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkDelayRequest.Merge(m, src)
}
func (m *WorkDelayRequest) XXX_Size() int {
	return xxx_messageInfo_WorkDelayRequest.Size(m)
}
func (m *WorkDelayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkDelayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkDelayRequest proto.InternalMessageInfo

func (m *WorkDelayRequest) GetWorkId() int64 {
	if m != nil {
		return m.WorkId
	}
	return 0
}

func (m *WorkDelayRequest) GetDelaySeconds() int64 {
	if m != nil {
		return m.DelaySeconds
	}
	return 0
}

type WorkDelayResponse struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkDelayResponse) Reset()         { *m = WorkDelayResponse{} }
func (m *WorkDelayResponse) String() string { return proto.CompactTextString(m) }
func (*WorkDelayResponse) ProtoMessage()    {}
func (*WorkDelayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed935c7c7e17eaaa, []int{22}
}

func (m *WorkDelayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkDelayResponse.Unmarshal(m, b)
}
func (m *WorkDelayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkDelayResponse.Marshal(b, m, deterministic)
}
func (m *WorkDelayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkDelayResponse.Merge(m, src)
}
func (m *WorkDelayResponse) XXX_Size() int {
	return xxx_messageInfo_WorkDelayResponse.Size(m)
}
func (m *WorkDelayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkDelayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkDelayResponse proto.InternalMessageInfo

func (m *WorkDelayResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *WorkDelayResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*AddWorkFlowRequest)(nil), "AddWorkFlowRequest")
	proto.RegisterMapType((map[string]string)(nil), "AddWorkFlowRequest.EnvEntry")
	proto.RegisterType((*AddWorkFlowResponse)(nil), "AddWorkFlowResponse")
	proto.RegisterType((*RecoverWorkFlowRequest)(nil), "RecoverWorkFlowRequest")
	proto.RegisterType((*RecoverWorkFlowResponse)(nil), "RecoverWorkFlowResponse")
	proto.RegisterType((*SetWorkFlowContextRequest)(nil), "SetWorkFlowContextRequest")
	proto.RegisterMapType((map[string]string)(nil), "SetWorkFlowContextRequest.ContextEntry")
	proto.RegisterType((*SetWorkFlowContextResponse)(nil), "SetWorkFlowContextResponse")
	proto.RegisterType((*GetWorkFlowContextRequest)(nil), "GetWorkFlowContextRequest")
	proto.RegisterType((*GetWorkFlowContextResponse)(nil), "GetWorkFlowContextResponse")
	proto.RegisterMapType((map[string]string)(nil), "GetWorkFlowContextResponse.ContextEntry")
	proto.RegisterType((*WorkResult)(nil), "WorkResult")
	proto.RegisterType((*QueryWorkRequest)(nil), "QueryWorkRequest")
	proto.RegisterType((*QueryWorkResponse)(nil), "QueryWorkResponse")
	proto.RegisterType((*QueryWorkFlowRequest)(nil), "QueryWorkFlowRequest")
	proto.RegisterType((*QueryWorkFlowResponse)(nil), "QueryWorkFlowResponse")
	proto.RegisterType((*FinishWorkFlowRequest)(nil), "FinishWorkFlowRequest")
	proto.RegisterType((*FinishWorkFlowResponse)(nil), "FinishWorkFlowResponse")
	proto.RegisterType((*WorkStartRequest)(nil), "WorkStartRequest")
	proto.RegisterType((*WorkStartResponse)(nil), "WorkStartResponse")
	proto.RegisterType((*WorkFinishRequest)(nil), "WorkFinishRequest")
	proto.RegisterType((*WorkFinishResponse)(nil), "WorkFinishResponse")
	proto.RegisterType((*WorkErrorRequest)(nil), "WorkErrorRequest")
	proto.RegisterType((*WorkErrorResponse)(nil), "WorkErrorResponse")
	proto.RegisterType((*WorkDelayRequest)(nil), "WorkDelayRequest")
	proto.RegisterType((*WorkDelayResponse)(nil), "WorkDelayResponse")
}

func init() { proto.RegisterFile("termite.proto", fileDescriptor_ed935c7c7e17eaaa) }

var fileDescriptor_ed935c7c7e17eaaa = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5f, 0x6f, 0x12, 0x4f,
	0x14, 0x65, 0xd9, 0x52, 0xda, 0x4b, 0xfb, 0xfb, 0x95, 0x5b, 0x0a, 0xdb, 0x55, 0x93, 0x76, 0x7c,
	0xb0, 0x89, 0xc9, 0x44, 0x6b, 0xa3, 0xa6, 0x4f, 0xd2, 0x5a, 0x9a, 0xda, 0x07, 0x15, 0x8c, 0x7d,
	0x31, 0x36, 0x94, 0x1d, 0x15, 0x4b, 0x19, 0xdc, 0x1d, 0xa8, 0x7c, 0x2e, 0x3f, 0x84, 0x89, 0x7e,
	0x29, 0x33, 0x7f, 0x16, 0x16, 0x58, 0x4a, 0xd9, 0xe8, 0xdb, 0xde, 0xb9, 0x33, 0xe7, 0x1e, 0xce,
	0xdc, 0x33, 0x17, 0x58, 0x15, 0xcc, 0xbf, 0x6a, 0x0a, 0x46, 0x3b, 0x3e, 0x17, 0x9c, 0xfc, 0xb6,
	0x00, 0xcb, 0x9e, 0x77, 0xc6, 0xfd, 0xcb, 0x4a, 0x8b, 0x5f, 0x57, 0xd9, 0xb7, 0x2e, 0x0b, 0x04,
	0x6e, 0xc3, 0xca, 0x35, 0xf7, 0x2f, 0x3f, 0xb5, 0xf8, 0xf5, 0xf9, 0x25, 0xeb, 0x3b, 0xd6, 0x96,
	0xb5, 0xb3, 0x5c, 0xcd, 0x85, 0x6b, 0xa7, 0xac, 0x8f, 0x0e, 0x64, 0x3b, 0x3e, 0xff, 0xca, 0x1a,
	0xc2, 0x49, 0xab, 0x6c, 0x18, 0x22, 0x05, 0x9b, 0xb5, 0x7b, 0x8e, 0xbd, 0x65, 0xef, 0xe4, 0x76,
	0xef, 0xd2, 0x49, 0x78, 0x7a, 0xd4, 0xee, 0x1d, 0xb5, 0x85, 0xdf, 0xaf, 0xca, 0x8d, 0xb8, 0x06,
	0x76, 0xa3, 0xe9, 0x39, 0x0b, 0x0a, 0x45, 0x7e, 0xba, 0x4f, 0x61, 0x29, 0xdc, 0x22, 0xb3, 0x43,
	0x06, 0xf2, 0x13, 0x0b, 0x90, 0xe9, 0xd5, 0x5b, 0x5d, 0x66, 0xea, 0xea, 0x60, 0x3f, 0xfd, 0xdc,
	0x22, 0x87, 0xb0, 0x3e, 0x52, 0x2d, 0xe8, 0xf0, 0x76, 0xc0, 0x10, 0x61, 0xa1, 0xc1, 0x3d, 0xa6,
	0x30, 0xec, 0xaa, 0xfa, 0x96, 0xf4, 0xaf, 0x58, 0x10, 0xd4, 0x3f, 0x87, 0x30, 0x61, 0x48, 0x1e,
	0x43, 0xb1, 0xca, 0x1a, 0xbc, 0xc7, 0xfc, 0x71, 0x55, 0x4a, 0x90, 0x55, 0x8a, 0x34, 0x3d, 0x03,
	0xb5, 0x28, 0xc3, 0x13, 0x8f, 0x1c, 0x43, 0x69, 0xe2, 0x48, 0xa2, 0xda, 0x3f, 0x2c, 0xd8, 0xac,
	0x31, 0x11, 0xa2, 0x1c, 0xf2, 0xb6, 0x60, 0xdf, 0xc5, 0xac, 0xfa, 0x58, 0x86, 0x6c, 0x43, 0x6f,
	0x75, 0xd2, 0x4a, 0xf5, 0x07, 0x74, 0x2a, 0x0a, 0x35, 0xa1, 0xbe, 0x80, 0xf0, 0x9c, 0xbb, 0x0f,
	0x2b, 0xd1, 0xc4, 0x5c, 0xb2, 0xbf, 0x02, 0x37, 0xae, 0x5c, 0x22, 0x05, 0xf6, 0x60, 0xf3, 0x78,
	0x6e, 0x01, 0xc8, 0x2f, 0x0b, 0xdc, 0xe3, 0xbf, 0x44, 0x01, 0x0f, 0x86, 0x6a, 0xea, 0x1e, 0xde,
	0xa1, 0xd3, 0xb1, 0xff, 0x81, 0x9c, 0xef, 0x01, 0x64, 0xb1, 0x2a, 0x0b, 0xba, 0x2d, 0x11, 0xba,
	0xc3, 0x1a, 0xb8, 0x43, 0xaa, 0x20, 0x8d, 0x28, 0x55, 0x48, 0x6b, 0x15, 0x64, 0x78, 0xe2, 0xe1,
	0x3d, 0x00, 0x95, 0x08, 0x44, 0x5d, 0x30, 0xc7, 0x56, 0xb9, 0x65, 0xb9, 0x52, 0x93, 0x0b, 0xe4,
	0x02, 0xd6, 0xde, 0x76, 0x99, 0xdf, 0xd7, 0xe0, 0xb7, 0x36, 0xfa, 0x26, 0x2c, 0x29, 0x54, 0x99,
	0x36, 0x4a, 0xc9, 0x58, 0xa6, 0x0c, 0x37, 0x7b, 0xc0, 0x8d, 0x78, 0x90, 0x8f, 0xd4, 0x30, 0xf2,
	0x6f, 0x43, 0x46, 0x9e, 0x08, 0x1c, 0x4b, 0xc9, 0x99, 0xa3, 0xc3, 0x9f, 0x57, 0xd5, 0x99, 0xc1,
	0x0d, 0xa5, 0xe3, 0x6f, 0xc8, 0x1e, 0x6d, 0x92, 0x53, 0x28, 0x0c, 0xaa, 0xcc, 0xf9, 0x6c, 0x19,
	0xca, 0xe9, 0x21, 0xe5, 0x8f, 0xb0, 0x31, 0x06, 0x66, 0x68, 0x4f, 0xb5, 0xdb, 0x7c, 0x64, 0x1f,
	0xc1, 0x46, 0xa5, 0xd9, 0x6e, 0x06, 0x5f, 0x6e, 0xfd, 0x9c, 0x54, 0xa0, 0x38, 0x7e, 0x22, 0x91,
	0x97, 0x1e, 0xc2, 0xda, 0x99, 0xbe, 0x7d, 0x3f, 0x6a, 0xa1, 0xb0, 0x79, 0xac, 0x68, 0xf3, 0x90,
	0x32, 0xe4, 0x23, 0x9b, 0x13, 0xd5, 0xfb, 0xa0, 0x21, 0x34, 0xf7, 0x59, 0x05, 0xb1, 0x08, 0x8b,
	0xbe, 0xea, 0x01, 0x03, 0x63, 0x22, 0xb9, 0xce, 0xbb, 0xa2, 0xd3, 0x15, 0x46, 0x48, 0x13, 0x91,
	0x03, 0xc0, 0x28, 0x7a, 0x22, 0x86, 0x65, 0xad, 0xc8, 0x91, 0xef, 0x73, 0x7f, 0x26, 0xc1, 0x02,
	0x64, 0x98, 0xdc, 0x18, 0x3a, 0x54, 0x05, 0xa1, 0x4e, 0x06, 0x22, 0x11, 0x8b, 0x37, 0x9a, 0xc5,
	0x4b, 0xd6, 0xaa, 0xf7, 0x67, 0xb2, 0xb8, 0x0f, 0xab, 0x9e, 0xdc, 0x78, 0x1e, 0xb0, 0x06, 0x6f,
	0x7b, 0x81, 0xe9, 0xba, 0x15, 0xb5, 0x58, 0xd3, 0x6b, 0x21, 0x29, 0x83, 0x98, 0x84, 0xd4, 0xee,
	0xcf, 0x0c, 0x64, 0xdf, 0xe9, 0xff, 0x06, 0xb8, 0x0f, 0xb9, 0xc8, 0x1c, 0xc5, 0xf5, 0x98, 0x19,
	0xee, 0x16, 0x68, 0xcc, 0xa8, 0x25, 0x29, 0x3c, 0x84, 0xff, 0x46, 0x9b, 0x17, 0x8b, 0x34, 0xb6,
	0xff, 0xdd, 0x12, 0x8d, 0xef, 0x72, 0x92, 0xc2, 0x0a, 0xfc, 0x3f, 0x36, 0x50, 0xb1, 0x44, 0xe3,
	0xa7, 0xb2, 0xeb, 0xd0, 0x29, 0xb3, 0x97, 0xa4, 0xf0, 0x35, 0xe0, 0xe4, 0xd3, 0x8d, 0x2e, 0x9d,
	0x3a, 0x62, 0xdc, 0x3b, 0x37, 0xbc, 0xf5, 0x1a, 0xb0, 0x16, 0x07, 0x58, 0xbb, 0x01, 0xb0, 0x76,
	0x13, 0xe0, 0x1e, 0x2c, 0x0f, 0x6c, 0x87, 0x79, 0x3a, 0xee, 0x57, 0x17, 0xe9, 0x84, 0x2b, 0x49,
	0x0a, 0x9f, 0xe9, 0x11, 0xa1, 0xf5, 0x43, 0xbd, 0x67, 0xc4, 0x76, 0xee, 0x3a, 0x9d, 0x34, 0xcb,
	0xb0, 0x9c, 0xea, 0x5e, 0x53, 0x2e, 0x6a, 0x06, 0x53, 0x6e, 0xa4, 0xb9, 0x87, 0xa7, 0x54, 0x7b,
	0x99, 0x53, 0xd1, 0xe6, 0x35, 0xa7, 0x46, 0xba, 0x8f, 0xa4, 0xf0, 0x05, 0xac, 0x8e, 0x3c, 0xac,
	0xb8, 0x41, 0xe3, 0x5e, 0x6d, 0xb7, 0x48, 0x63, 0xdf, 0x5f, 0x5d, 0x77, 0x90, 0xc2, 0x3c, 0x1d,
	0x9f, 0x5e, 0x2e, 0xd2, 0x89, 0x61, 0x43, 0x52, 0x17, 0x8b, 0xea, 0xaf, 0xed, 0x93, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x26, 0x8a, 0xe9, 0x15, 0xeb, 0x0a, 0x00, 0x00,
}
